### ISSUE TITLE
[Feat] 프로젝트 페이지 firebase 데이터 연동

### ISSUE THREAD

**Issue by skyeome** [im-na0/wiki#18]
## 세부 내용
firebase firestore 기능을 사용해서 데이터 베이스에 데이터를 저장하고
저장한 데이터를 CRUD 구현하는것을 목표로 하고 있습니다.

## TODO
- [x] 칸반 보드 드래그 & 드롭시 수정된 내용 firebase에 적용하기
- [x] 프로젝트 상세 보기 기능 구현
- [x] 프로젝트 수정 기능 구현
- [x] 프로젝트 삭제 기능 구현
- [x] 프로젝트 목록 보기 기능 구현
