### ISSUE TITLE
[Feat] 직원 휴가 내역 캘린더 및 Timer 페이지 DB 연동

### ISSUE THREAD

**Issue by mysdpy30s** [im-na0/wiki#32]
## 세부 내용
WorkTime 페이지 캘린더에 팀원 휴가 내역 표시 및 Timer 페이지 파이어베이스 연동 작업

## TODO
- [ ] 캘린더 휴가 내역 파이어베이스 연동
- [x] Timer 버튼에 출퇴근 기록 기능 추가 및 파이어베이스 연동
- [x] Timer 모달창 구현
