### ISSUE TITLE
[Feat] 팀 리스트 페이지 마크업

### ISSUE THREAD

**Issue by im-na0** [im-na0/wiki#49]
## 세부 내용
- 직원 페이지 Nav를 생성할 예정입니다

## TODO
- [x] 팀 리스트 페이지 마크업
- [x] 팀 추가 모달창 마크업
- [x] 직원 페이지 Nav 생성
