### ISSUE TITLE
[Feat] Project 페이지 마크업

### ISSUE THREAD

**Issue by skyeome** [im-na0/wiki#5]
## 세부 내용
프로젝트 페이지 마크업이 필요하여 진행하고자 합니다.

## TODO
- [x] 프로젝트 칸반 보드 페이지
- [x] 프로젝트 자세히 보기 페이지
- [x] 프로젝트 생성 페이지
