### ISSUE TITLE
[Feat] 위키페이지 팀 폴더 생성

### ISSUE THREAD

**Issue by NohWookJin** [im-na0/wiki#57]
## 세부 내용
유저의 로그인 여부에 따른 폴더 목록 생성/비생성 
* 로그인 O => 공용 폴더 목록 활성화 / 팀 이름, 팀 폴더 버튼, 팀 폴더 목록 활성화
* 로그인 X => 공용 폴더 목록 활성화 / 팀 이름, 팀 폴더 버튼, 팀 폴더 목록 비활성화

## TODO
- [x] 유저 컬렉션 연결
- [x] 유저에 따른 팀 폴더 생성 버튼 활성화
- [x] 팀에 따른 팀 폴더 필드 구분
