### ISSUE TITLE
[Feat] 팀 상세정보 페이지 업로드 로딩 기능

### ISSUE THREAD

**Issue by im-na0** [im-na0/wiki#63]
## 세부 내용
팀 상세정보 페이지 업로드 로딩 및 다른 기능들을 구현할 예정입니다.

## TODO
- [x] 팀 상세정보페이지 readonly 적용하기
- [x] 팀 상세정보페이지 목록으로 되돌아가기 버튼 만들기
- [x] 팀 상세정보페이지 업데이트 시 spin 구현
