### ISSUE TITLE
[Feat] 팀 페이지 추가 기능 구현

### ISSUE THREAD

**Issue by im-na0** [im-na0/wiki#77]
## 세부 내용
팀 페이지 추가 기능을 구현할 예정 입니다.

## TODO
- [x] 팀 리스트 페이지 대표사진 프로필 표시
- [x] 가능하다면 ui 변경
- [x] 팀 상세페이지 정보필드 추가하기
- [x] 팀 상세 페이지 팀원 정보 추가하기
- [ ] 팀 프로젝트와 팀 위키와 연동할 수 있다면 간단한 상태 보여주기
