### ISSUE TITLE
[Feat] 캘린더 기능 추가 및 기타 사항 보완

### ISSUE THREAD

**Issue by mysdpy30s** [im-na0/wiki#78]
## 세부 내용
캘린더 기능 추가 및 그 외 구현된 기능 보완 예정입니다.

## TODO
- [x] 캘린더 출퇴근 기록 실시간 반영되도록 수정
- [ ] 캘린더 날짜 칸에 출력할 내용이 길어질 경우 미니 모달창으로 내용 표시
- [ ] 캘린더 휴가 내역 출력 (선택사항)
- [x] 기타 기능 에러 수정 및 보완
