### ISSUE TITLE
[Feat] 멤버 삭제 시 팀 콜렉션 userId도 삭제

### ISSUE THREAD

**Issue by im-na0** [im-na0/wiki#91]
## 세부 내용
- 멤버를 등록 할 때 팀 콜렉션의 userId에도 같이 등록되는 구조라, 멤버 삭제할 때도 팀 콜렉션의 userId에서 삭제되는 로직을 만들어야할 것 같습니다 

## TODO
- [x] userId 배열 중복값 제외시키기
- [x] 멤버 삭제 시 해당 팀의 userId도 같이 삭제되게 하기
- [ ] 팀리더 셀렉트 옵션에서 현재 팀원이 필터링 처리됨 해결하기
